### ISSUE TITLE
Creating non-element nodes

### ISSUE THREAD

**Issue by jcf120** [shortercode/Doom.js#11]
I want to generate the following:

``` html
<span></span>&nbsp;<span></span>
```

From what I can [see](http://stackoverflow.com/questions/10951340/create-a-blank-html-space-on-the-fly-javascript/10951405#10951405), we'd need support for `document.createTextNode`. What do you think of having something like?:

``` javascript
Doom.create({
    childNodes: [
        { tagName: 'span' },
        { textNode: '\u00A0' },
        { tagName: 'span' }
    ]
});
```

**Comment by shortercode** [comment]
mmm interesting idea, I believe you can do this already using

```
Doom.create({
    childNodes: [
        { tagName: 'span' },
        "&nbsp;",
        { tagName: 'span' }
    ]
});
```

The child attribute can take a String, an HTMLElement or an Object. When used in string mode it creates a temporary node, sets the innerHTML to the string then moves the childNodes from the temp node to the parent. So in theory you can create textNodes using it, in a slightly roundabout way. I was never sure I really liked the way this behaved though. 

Supporting `Doom.create({textNode: "mytext"})` would basically be a completely new branch for createElement, and none of the existing parameters would really make sense for a textNode...

We could potentially add a new method like `Doom.text("mytext")` which returned a textNode, but it would basically be an alias for `new Text("myText")`.

Alternatively we could modify the String mode on the child attribute to only create a textNode, but that's a breaking change. I know I used that feature somewhere in either web timing or paddock club, most likely the latter.

**Comment by shortercode** [comment]
by the way `new Text()` is basically the same as `document.createTextNode()` but from one of the newer spec documents

**Comment by jcf120** [comment]
Ah, I did not know that `create` could take string children. Well, I'm happy with that. Yeah, I suppose it's not the most direct impl - probs not expensive though right?

**Comment by shortercode** [comment]
well it's probably "fast enough" there's a couple of alternate methods that might be faster but I haven't tested them.

current implementation:

```
var temp = Doom.create({
    innerHTML: node
});
while (temp.firstChild) {
    this.appendChild(temp.firstChild);
}
```

an alternative without the overhead of calling `Doom.create`

```
var temp = document.createElement('div');
temp.innerHTML = node;
while (temp.firstChild)
    this.appendChild(temp.firstChild);
```

or using HTML templates, which has less legacy support

```
var temp = document.createElement('template');
temp.innerHTML = node;
this.appendChild(temp.content);
```

**Comment by shortercode** [comment]
`.content` is specific to the HTMLTemplateElement prototype and returns a document fragment. 

Supposedly `document.createRange().createContextualFragment(htmlstring)` will create a document  fragment from a string, but it's... a little odd. But yeah given that it's a single append operation with a fragment it _should_ be faster

**Comment by jcf120** [comment]
Seems IE doesn't support templates. Range is from IE 11. Maybe a thing to change if you discover you're losing out.
