### ISSUE TITLE
Remove delegate class?

### ISSUE THREAD

**Issue by shortercode** [shortercode/Doom.js#19]
So the delegate class, as far as I'm aware, has never been used. It was requested ages ago by someone and then wasn't needed. It isn't exceptionally useful, and as such I think it should be removed. Any arguments against @jcf120 ?

**Comment by jcf120** [comment]
I didn't even know it was there, so probably not. I suppose I might have used it, but I'd be just as happy including it separately. It's not really DOM related.

**Comment by shortercode** [comment]
Yeah I've always thought it was a bit out of the scope. I've been using the atom event kit recently, which I think is way better. Uses a system called disposables. So calling `dispatcher.on(eventName, eventHandler)` returns an instance of `Disposable`, that then has a method to remove the event handler. Also has collections for them as well, so you can remove all the event handlers for a class covering several dispatchers. Great for complicated MVC stuff, have replaced stuff like this:

```javascript
class App {
    constructor (layout) {
        this.layout = layout;
        this._loadHandler = () => this._onLoad();
        this._resizeHandler = () => this._onResize();
        window.addEventListener('load', this._loadHandler, false);
        layout.addEventListener('resize', this._resizeHandler, false);
    }
    release () {
        window.removeEventListener('load', this._loadHandler, false);
        layout.removeEventListener('resize', this._resizeHandler, false);
        this._loadHandler = null;
        this._resizeHandler= null;
        this.layout = null;
    }
}
```
with this
```javascript
class App {
    constructor (layout) {
        this.layout = layout;
        this.subscribers = new CompositeDisposable(
            Disposable.from(window, 'load'),
            Disposable.from(layout, 'resize')
        );
    }
    release () {
        this.subscribers.dispose();
        this.layout = null;
        this.subscribers = null;
    }
}
```

so yeah goes from *3n* lines per handler to *n + 3*. Incidentally `.From` was a method I added for wrapping native `EventTarget` objects, the library built in `EventDisptacher` returns Disposable instances.

Anyway, back on topic, I'm going to remove the delegate class today.
