### ISSUE TITLE
Extending attributes

### ISSUE THREAD

**Issue by jcf120** [shortercode/Doom.js#22]
We're looking to integrate localisation into Doom, enabling something like:
```javascript
Doom.create({
    innerHTML: '<p>_{Text to be translated}</p>'
});
```
Perhaps we could expose the attributes, and have the ability to extend them:
```javascript
Doom.defineAttribute('transHTML', function(arg) {
    Doom.attributes.innerHTML.apply(this, ourTranslationFunc(arg) );
});

Doom.create({
    transHTML: '<p>_{Text to be translated}</p>'
});
```
Thoughts?

**Comment by shortercode** [comment]
Not a bad idea, be nice to introduce some more modularity. I'd always
envisgned a collection of libraries for alloy components but never got
around to building any...  Anyway I think we should use
`Doom.create.defineAttribute` and `Doom.modify.defineAttribute` as they can
have differing behaviours. There's a few things you cannot implement
without access to the actual base method (like the reference system we
introduced) but this should allow most new features. Also if you haven't
written the translation system yet I have some WIP code for mustache style
templates, was originally intended for live data binding so you can
probably slim it down a bit for your use.

**Comment by shortercode** [comment]
Okay I've committed a change for that to master, let me know how well it works!

**Comment by jcf120** [comment]
Oh sweet, that was quick!

**Comment by shortercode** [comment]
Yeah was a pretty simple change, basically just tagged on a `if (!key in
attributes) attributes [key] = value;` sort of method

**Comment by jcf120** [comment]
Alright if I add:
```javascript
createElement.attributes = attributes;
//...
modifyElement.attributes = attributes;
```
Else I don't see how to wrap around an existing attribute, such as `innerHTML`.

**Comment by shortercode** [comment]
Well the intention was to not allow the built-in methods to be overloaded.

I mean modifying the code to allow an overload is pretty easy, we just need
to remove the `key in attributes` check from the methods I added the other
day. But it seems like a bad idea to modify the behaviour of a base method,
as you could no longer use it for its original purpose.

I would recommend just using a different property name, like so

Doom.create.define("lang", function (v) {
  this.textContent = lang(v);
});

Also for pure text content it's safer to use 

Doom.create({textContent: "hello world"});

than innerHTML as it doesn't go through the HTML parser
(might also be faster, never checked).

**Comment by jcf120** [comment]
The aim was to go through the parser:
```
'<p>_{Text to be translated}</p>'
```
I see where I was confused now. I forgot that `innerHTML` was being set on the elem directly, rather than through a Doom specific attribute. Anyway, s'all goood!

**Comment by shortercode** [comment]
Ah perhaps I misunderstood, I thought you meant to replace it not to inherit from it?

Could add something like:

```javascript
Doom.create.extend("lang", "innerHTML", function (v) {
  return lang(v); // return value is passed to original method
});

// possible implementation

function extend(newMethod, oldMethod, fn) {
  var m = attributes[oldMethod];
  if (!m)
    m = function (v) { this[oldMethod] = v}; // for if the value isn't part of attributes, just a HTMLElement method
  attributes[newMethod] = function (v) { // only ever single argument
    v = fn.call(this, v);  // maintain context
    m.call(this, v);
  };
}
```

**Comment by jcf120** [comment]
Yeah, that's more like what I was aiming for. Neat.
