### ISSUE TITLE
Dragging gesture isn't cancelled when leaving browser window and releasing

### ISSUE THREAD

**Issue by Jac3kC** [shortercode/Doom.js#25]
The issue can be reproduced in gestures.html. Try clicking and holding the mouse button in touch area to start "pan" event, then move the cursor off the window and release the button. When returning to the touch area the "pan" will be still ongoing.

**Comment by shortercode** [comment]
I think this is happening because the mouseup event is firing while the
cursor is offscreen. If we change the event binding to window instead of
body it should fix the problem

**Comment by jcf120** [comment]
Your suggestion works a treat with the desktop browser. Sadly not so with the Android webview. Maybe the events'll need spoofing by native.

**Comment by shortercode** [comment]
We'll i know a trick for mouse events which could solve this, but I'm not
sure if there an equivalent for touch events. It's possible that you could
store a reference to the touch objects in event.touches and check for
changes... But I expect the webview/uiview mix is preventing the touch
cancel to fire at the useragent level.

Is this issue causing an invalid gesture or something?

**Comment by jcf120** [comment]
Yeah, I've built a  twitter-style drag-down-to-refresh component that locks if you drag beyond the webview frame. Cheers, I'll try watching the touches - see if that gets me anywhere.

**Comment by jcf120** [comment]
The `changedTouches` stop changing. Ah well.

**Comment by shortercode** [comment]
I kinda guessed they would, the webview has lost track of the touches...
Which is a little weird but not impossible obviously.

The best the library can probably do is reset the gesture if the next event
is a different touch object, but that could cause multi touch related
issues. So will be a little fiddly to implement.

I would recommend building a timeout into the component. Say if no move
events have fired in 500 ms either trigger the refresh or cancel based on
the current offset.

**Comment by jcf120** [comment]
Jacek got native to manually prompt the event, so it's all good!
